# Copyright (C) 2026 Qt Group.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only

[Controls]
Style=Material
FallbackStyle=Basic

[Material]
Theme=Light
Accent=Purple
Variant=Dense
Foreground=Pink
Font\PointSize=12

[Universal]
Theme=System
Accent=Red

[Fusion]
Palette\Window=LightBlue
Palette\WindowText=Purple
