[Controls]
Style=Material
FallbackStyle=Basic

[Material]
Theme=Light
Accent=Purple
Variant=Dense
Foreground=Pink
Font\PointSize=12

[Universal]
Theme=System
Accent=Red

[Fusion]
Palette\Window=LightBlue
Palette\WindowText=Purple
